# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Start Local Development Server
        run: npm start &

      - name: Wait for Server to Be Ready
        run: |
          echo "Waiting for the server to be available..."
          for i in {1..30}; do
            if curl -s http://localhost:3000; then
              echo "Server is up!"
              break
            fi
            echo "Waiting..."
            sleep 5
          done

      - name: Run Tests On CI Environment
        env:
          BASE_URL: http://localhost:3000/
        run: npm run test

      - name: Run Tests On Live App
        env:
          BASE_URL: https://milanmihajlovic39.github.io/simple-web-app/
        run: npm run test
